CREATE DATABASE DasProjeDB
GO
USE DasProjeDB
GO

CREATE TABLE tblCari(
CariId INT PRIMARY KEY IDENTITY,
Unvan NVARCHAR(50) NOT NULL,
Ad NVARCHAR(50) NOT NULL,
Soyad NVARCHAR(50) NOT NULL,
Adres NVARCHAR(50),
Telefon NVARCHAR(50)
)

CREATE TABLE tblCariHareketleri(
Id INT PRIMARY KEY IDENTITY,
CariId INT NOT NULL,
Tarih DATETIME NOT NULL,
IslemTipi NVARCHAR(50) NOT NULL,
IslemTuru NVARCHAR(50) NOT NULL,
Borc MONEY,
Alacak MONEY,
Aciklama NVARCHAR(100),
FOREIGN KEY (CariId) REFERENCES tblCari(CariId)
)